baseURL = 'https://www.primebroth.co.nz/'
languageCode = 'en-us'
title = 'PrimeBroth'
theme = 'tella'

[params]
  defaultTheme = "light"
  disableThemeToggle = true

  [params.homeInfoParams]
    Title = "Elevate Wellness, One Sip at a Time"
    Content = "Our premium drinkable nutrition offers a delicious and convenient way to nourish your body, crafted with care in NZ for your health and vitality.<br><br>Questions? Contact us at hello@primebroth.co.nz"

  [[params.socialIcons]]
    Name = "facebook"
    Url = "https://facebook.com/"
  [[params.socialIcons]]
    Name = "twitter"
    Url = "https://twitter.com/"

  [params.cover]
    linkFullImages = true

  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

[params.logo]
    main = "img/logo/logo.webp"


[menu]

  [[menu.main]]
    identifier = "shop"
    name = "Shop"
    url = "/shop/"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/pages/about/"

  [[menu.main]]
    identifier = "recipes"
    name = "Recipes"
    url = "/recipes/"

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"

  [[menu.footer]]
    identifier = "terms_of_use"
    name = "Terms of Use"
    url = "/pages/terms-of-use/"

  [[menu.footer]]
    identifier = "privacy_policy"
    name = "Privacy Policy"
    url = "/pages/privacy-policy/"

  [[menu.footer]]
    identifier = "delivery"
    name = "Delivery"
    url = "/pages/delivery/"

  [[menu.footer]]
    identifier = "refund_policy"
    name = "Refund Policy"
    url = "/pages/refund-policy/"

  [[menu.footer]]
    identifier = "manage_subscriptions"
    name = "Manage Subscriptions"
    url = "/pages/manage-subscription/"




[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
linkify = false
