baseURL = 'https://www.primebroth.co.nz/'
languageCode = 'en-us'
title = 'PrimeBroth'
theme = 'tella'

[build]
draft = true
future = true
expired = true

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  description = "The bone broth company making the most rich and nutritious bone broth in Christchurch. The best bone broth for making picky pets piggy."

  [params.homeInfoParams]
    Title = "Elevate Wellness, One Sip at a Time"
    Content = "Our premium drinkable nutrition offers a delicious and convenient way to nourish your body, crafted with care in NZ for your health and vitality.<br><br>Questions? Contact us at hello@primebroth.co.nz"

  [[params.socialIcons]]
    Name = "facebook"
    Url = "https://facebook.com/"
  [[params.socialIcons]]
    Name = "twitter"
    Url = "https://twitter.com/"

  [params.cover]
    linkFullImages = true

  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

[params.logo]
    main = "img/logo/logo.webp"

[params.homepage_meta_tags]
    meta_og_image = "img/banner.webp"
    meta_og_title = "Best bone broth for kiwis and their pets"
    meta_og_description = "The bone broth company making the most rich and nutritious bone broth in Christchurch. The best bone broth for making picky pets piggy."


[menu]

  [[menu.main]]
    identifier = "shop"
    name = "Shop"
    url = "/shop/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/pages/about/"
    weight = 1


  [[menu.footer]]
    identifier = "charity"
    name = "Charity"
    url = "/charity/"
    weight = 10

  [[menu.main]]
    identifier = "wholesale"
    name = "Wholesale"
    url = "/wholesale/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

    [[menu.main]]
    identifier = "markets"
    name = "Markets"
    url = "/upcoming-markets/"
    weight = 4

  [[menu.footer]]
    identifier = "terms_of_use"
    name = "Terms of Use"
    url = "/pages/terms-of-use/"
    weight = 6


  [[menu.footer]]
    identifier = "privacy_policy"
    name = "Privacy Policy"
    url = "/pages/privacy-policy/"
    weight = 7

  [[menu.footer]]
    identifier = "sitemap"
    name = "Sitemap"
    url = "/sitemap/"
    weight = 9


  [[menu.footer]]
    identifier = "delivery"
    name = "Delivery"
    url = "/pages/delivery/"
    weight = 6


  [[menu.footer]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 8

  [[menu.footer]]
    identifier = "refund_policy"
    name = "Refund Policy"
    url = "/pages/refund-policy/"
    weight = 5

  [[menu.footer]]
    identifier = "partner"
    name = "Partners"
    url = "/partner/"
    weight = 4

  [[menu.footer]]
      identifier = "faq"
      name = "FAQs"
      url = "/faq/"
      weight = 1


  [[menu.footer]]
      identifier = "reviews"
      name = "Reviews"
      url = "/pages/reviews/"
      weight = 2


[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
linkify = false
