baseURL = 'https://primebroth.co.nz/'
languageCode = 'en-us'
title = 'PrimeBroth'
theme = 'tella'


[params]
  defaultTheme = "light"
  disableThemeToggle = true

  [params.homeInfoParams]
    Title = "COMING SOON<br><br>Elevate Wellness, One Sip at a Time"
    Content = "Our premium drinkable nutrition offers a delicious and convenient way to nourish your body, crafted with care in NZ for your health and vitality.<br><br>Questions? Contact us at hello@primebroth.co.nz"

  [[params.socialIcons]]
    Name = "facebook"
    Url = "https://facebook.com/"
  [[params.socialIcons]]
    Name = "twitter"
    Url = "https://twitter.com/"

  [params.cover]
    linkFullImages = true

  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true



[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
linkify = false
